### PR TITLE
Remove comment to pass CI

### PR DESCRIPTION
**Pull request by ayakoakasaka**
Fix https://github.com/midokura/wasi-sensor-discussion/actions/runs/7492879187/job/20397366849

### CODE REVIEW

**Comment by yamt** [comment]
> Fix https://github.com/midokura/wasi-sensor-discussion/actions/runs/7492879187/job/20397366849

this log is ephemeral.
please cite the relevant part of the message instead of just an url.

have you investigated why wit-bindgen changed the behavior while we are pinning its version?

**Comment by yamt** [comment]
see https://github.com/midokura/wasi-sensor-discussion/pull/40

**Comment by ayakoakasaka** [comment]
ok. understand.
I thought I had to follow this comment 

> Proposals should remove these `//` commments, and edit the `world` name and imports below to pull in their own `interface`s.

**Comment by ayakoakasaka** [comment]
Let me close it

**Pull request closed without merging**
