### PR TITLE
renovate.json: disable renovate

### PR DESCRIPTION
**Pull request by yamt**
* for this particular repo, it isn't that important to keep dependencies up to date.

* i got tired to resolve conflicts between renovate's changes and my changes.

### CODE REVIEW

**Review by ayakoakasaka — COMMENTED** [review]
This means disabling all package updates. 
Is it hard to keep up with updates?

**Comment by yamt** [comment]
> This means disabling all package updates. Is it hard to keep up with updates?

as mentioned in the commit message, i don't think it's important to keep us updated.

also, we already disabled renovate for important packages.

**Review by ayakoakasaka — COMMENTED** [review]
Unless you have a strong request, I would like to keep this Repo up to date. 
Last time we pause wasmtime and wit-bindgen not to break the on going implementation. But basically I want to allow to update if CI/CD pass

**Comment by yamt** [comment]
> Unless you have a strong request, I would like to keep this Repo up to date. Last time we pause wasmtime and wit-bindgen not to break the on going implementation. But basically I want to allow to update if CI/CD pass

then, please stop merging these PRs when it creates conflicts.

**Comment by ayakoakasaka** [comment]
well noted

**Pull request closed without merging**
